networks:
  nlp-project:
    driver: bridge

services:
  streamlit:
    image: ghcr.io/khantzawhein/nlp-project-streamlit:latest
    container_name: streamlit
    restart: unless-stopped
    depends_on:
        - mongodb
        - redis
    networks:
      - nlp-project
    ports:
      - "8501:8501"
    environment:
      - "MONGO_URI=mongodb://root:B0d9LvwuUHXn91DU7DiX0k4@mongodb:27017"
      - "REDIS_URI=redis://redis:6379"
      - "MONGO_DB=text_analysis_db"
    volumes:
      - ./app:/app
      - ./ner_model:/app/ner_model
      - ./docker-data/flair:/root/.flair
    entrypoint: "streamlit run main.py --server.port=8501 --server.address=0.0.0.0"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    networks:
      - nlp-project
    volumes:
      - ./docker-data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "B0d9LvwuUHXn91DU7DiX0k4"
      MONGO_INITDB_DATABASE: "text_analysis_db"
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - nlp-project
    restart: unless-stopped
    volumes:
      - ./docker-data/redis:/data
  worker:
    image: ghcr.io/khantzawhein/nlp-project-streamlit:latest
    restart: unless-stopped
    container_name: worker
    networks:
      - nlp-project
    depends_on:
      - redis
    volumes:
      - ./app:/app
      - ./ner_model:/app/ner_model
      - ./docker-data/flair:/root/.flair
    environment:
      - "MONGO_URI=mongodb://root:B0d9LvwuUHXn91DU7DiX0k4@mongodb:27017"
      - "REDIS_URI=redis://redis:6379"
      - "MONGO_DB=text_analysis_db"
    entrypoint: celery -A tasks.analyze_text worker --loglevel=INFO
